from typing import Awaitable, Callable

from fastapi import Request, Response
from loguru import logger


async def log_requests_middleware(request: Request, call_next: Callable[[Request], Awaitable[Response]]) -> Response:
    """
    Middleware for logging incoming HTTP requests and outgoing responses.

    Logs the following details:
        - HTTP method and URL of the request.
        - Status code of the response.

    Args:
        request (Request): The incoming HTTP request.
        call_next (Callable): A function to forward the request to the next middleware or route.

    Returns:
        Response: The response generated by the downstream middleware or route.
    """
    logger.info(f"Request: {request.method} {request.url}")
    response = await call_next(request)
    logger.info(f"Response status: {response.status_code}")
    return response
