from fastapi import Request
from fastapi.responses import RedirectResponse


async def trailing_slash_handler_middleware(request: Request, call_next):
    """
    Middleware to standardize URLs by removing trailing slashes.
    Redirects requests ending with '/' to the same URL without it.

    Args:
        request (Request): The incoming HTTP request.
        call_next (function): The next middleware or route handler.

    Returns:
        Response: Either a redirected response or the original response.
    """
    url = request.url.path
    query_string = request.url.query  # Correctly extract the query string

    if url != "/" and url.endswith("/"):  # Remove trailing slash
        new_url = url.rstrip("/")
        # Reconstruct URL with query parameters if they exist
        full_url = f"{new_url}?{query_string}" if query_string else new_url
        return RedirectResponse(url=full_url, status_code=307)

    return await call_next(request)

#
# async def log_requests_middleware(request: Request, call_next):
#     """
#     Middleware for logging incoming HTTP requests and outgoing responses.
#
#     Logs the following details:
#         - HTTP method and URL of the request.
#         - Status code of the response.
#
#     Args:
#         request (Request): The incoming HTTP request.
#         call_next (Callable): A function to forward the request to the next middleware or route.
#
#     Returns:
#         Response: The response generated by the downstream middleware or route.
#     """
#     logger.info(f"Request: {request.method} {request.url}")
#     response = await call_next(request)
#     logger.info(f"Response status: {response.status_code}")
#     return response
